### PR TITLE
ci: run lint when running on Linux

### PR DESCRIPTION
**Pull request by sebastiaanspeck**
Run lint when running on Linux

### CODE REVIEW

**Comment by clason** [comment]
I am _not_ a fan of "fail fast" workflows, which force you to CI golf. (Fix one issue, only to find out that the next test fails as well -- which you could have fixed at the same time had you known about it.)

**Comment by clason** [comment]
Unless we _know_ that further tests are worthless, we shouldn't cancel them, period.

**Comment by clason** [comment]
Sure; this is all work in progress. We _just_ started this.

**Comment by clason** [comment]
Sure; just be aware that you might be jumping the gun on things that are being worked on under the hood.

**Comment by clason** [comment]
Anyway, my point is just about skipping test steps. The rest is for @ObserverOfTime to manage.

**Comment by ObserverOfTime** [comment]
We appreciate the effort but this is all a WIP so actions and workflows are subject to change.
We won't enable linting out of the box (yet) since most of our parsers don't have it.

The workflow can be modified in individual repos, as you mentioned.

> Or do:
> 
> ```
> …
>       - name: Run tests
>         uses: tree-sitter-grammars/actions/test@main
>         with:
>           lint: ${{runner.os == 'Linux'}}
>           test-library: ${{runner.os == 'Linux'}}
> …
> ```

**Pull request closed without merging**
